import { PDF_MARGIN_MM, TABLE_WIDTH_MM } from './tableLayout';

export const INFO_COLUMN_GAP_MM = 10;
export const INFO_LABEL_WIDTH_LEFT_MM = 35;
export const INFO_LABEL_WIDTH_RIGHT_MM = 38;

const INFO_BLOCK_WIDTH_MM = (TABLE_WIDTH_MM - INFO_COLUMN_GAP_MM) / 2;
export const INFO_VALUE_WIDTH_LEFT_MM =
  INFO_BLOCK_WIDTH_MM - INFO_LABEL_WIDTH_LEFT_MM - 4;
export const INFO_VALUE_WIDTH_RIGHT_MM =
  INFO_BLOCK_WIDTH_MM - INFO_LABEL_WIDTH_RIGHT_MM - 4;

export const INFO_LEFT_X_MM = PDF_MARGIN_MM;
export const INFO_RIGHT_X_MM = PDF_MARGIN_MM + INFO_BLOCK_WIDTH_MM + INFO_COLUMN_GAP_MM;

export const INFO_LINE_HEIGHT_MM = 5;
